# Generated by Django 5.0.7 on 2025-01-04 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_alter_tweet_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet.profile'),
        ),
    ]
