# Generated by Django 5.0.7 on 2025-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Explore/photo/')),
                ('photo_desc', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to='Explore/video/')),
                ('video_desc', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(upload_to='storyvideos/'),
        ),
    ]
