# Generated by Django 5.0.7 on 2025-01-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0011_explorephoto_alter_story_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExplorePhoto',
            new_name='Explore',
        ),
    ]
