# Generated by Django 5.0.7 on 2025-01-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0012_rename_explorephoto_explore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Explore/photo/'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Explore/video/'),
        ),
    ]
