# Generated by Django 5.0.7 on 2025-01-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0013_alter_explore_photo_alter_explore_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='photo_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='explore',
            name='video_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
