# Generated by Django 5.0.7 on 2025-01-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0014_alter_explore_photo_desc_alter_explore_video_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='photo',
            field=models.ImageField(blank=True, default='Explore/photo/default_image.jpg', null=True, upload_to='Explore/photo/'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='video_desc',
            field=models.CharField(blank=True, default='Explore/video/default_video.mp4', max_length=250, null=True),
        ),
    ]
