# Generated by Django 5.0.7 on 2025-01-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0015_alter_explore_photo_alter_explore_video_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='video',
            field=models.FileField(blank=True, default='Explore/video/default_video.mp4', null=True, upload_to='Explore/video/'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='video_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
