# Generated by Django 5.0.7 on 2025-01-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0016_alter_explore_video_alter_explore_video_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='video',
            field=models.FileField(blank=True, default='Explore/video/default_video2.mp4', null=True, upload_to='Explore/video/'),
        ),
    ]
