# Generated by Django 5.0.7 on 2025-01-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0017_alter_explore_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='number_comment',
            field=models.IntegerField(default=0),
        ),
    ]
