# Generated by Django 5.0.7 on 2025-01-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0018_tweet_number_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='number_comment',
            new_name='save_comment',
        ),
    ]
