# Generated by Django 5.0.7 on 2025-01-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0020_profile_bio_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='https://www.linkedin.com/in/manoj-nayak-0222b1229/', max_length=250),
        ),
    ]
