# Generated by Django 5.0.7 on 2025-01-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0021_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg', upload_to='profile_pic/'),
        ),
    ]
