# Generated by Django 5.0.7 on 2025-01-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0022_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/'),
        ),
    ]
