# Generated by Django 5.0.7 on 2025-01-22 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0024_alter_story_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='tweet.profile'),
            preserve_default=False,
        ),
    ]
