# Generated by Django 5.0.7 on 2025-01-22 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0025_story_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tweet.profile'),
        ),
    ]
